### ISSUE TITLE
 example-deepdream CUDA Error

### ISSUE THREAD

**Issue by AndreasRef** [mrzl/ofxDarknet#6]
When running example-deepdream I get the following error.

```
Loading weights from /Users/andreasrefsgaard/Documents/OpenFrameworks/of_v0.9.7_osx_release/addons/ofxDarknet/example-deepdream/bin/data/vgg-conv.weights...Done!
Iteration: 0, 1, 2, CUDA Error: out of memory
Assertion failed: (0), function check_error, file /Users/sonneundasche/programming/of/addons/ofxDarknet/libs/darknet/include/cuda.c, line 39.
```

Is it suppose to refer to the local path of _/Users/sonneundasche/_ ?

**Comment by schwittlick** [comment]
what you have there is two issues. first, you are running out of memory. try to create a deep dream on a smaller image and you will run through more iterations and might eventually complete it, depending on the parameters you used.

the fact that the filesystem path from @BildPeter is showing up there is another issue that is not responsible for the crash.

**Comment by AndreasRef** [comment]
Ah, of course, just assumed they were somehow related. Smaller image size did the trick, thanks!

**Comment by schwittlick** [comment]
coolio :)

@BildPeter do you think there is any way of compiling the static lib in a way to use relative paths in these error messages?

**Comment by peterkolski** [comment]
@mrzl The filesystem is baked in automatically during generation of the lib. This should not matter while executing, if the run & linker path is set correctly.
@AndreasRef Is this still occurring with sufficient memory? Otherwise the issue is closed.
